MAIN_WND = 'MAIN_WND'

STEPS_TBL = f'--{MAIN_WND}::STEPS_TABLE--'
RESULTS_TBL = f'--{MAIN_WND}::RESULTS_TABLE--'

DEVICES_INP = f'--{MAIN_WND}::DEVICES_INP--'
SOURCES_INP = f'--{MAIN_WND}::SOURCES_INP--'
BUFFER_INP = f'--{MAIN_WND}::BUFFER_INP--'
MAX_REQ_INP = f'--{MAIN_WND}::MAX_REQ_INP--'

MAIN_WND_INPUTS = [DEVICES_INP, SOURCES_INP, BUFFER_INP, MAX_REQ_INP]

STEP_BTN = 'Step'
AUTO_BTN = 'Auto'
RESET_BTN = 'Reset'
APPLY_BTN = 'Apply'
